# config.py
import os


DATA_DIR = os.environ.get("GIM_BOT_DATA_DIR", "data")
HISCORES_URL = "https://secure.runescape.com/m=hiscore_oldschool/index_lite.ws?player="

SKILL_ROW_ORDER = ['Total', 'Attack', 'Defense', 'Strength',
                       'Hitpoints', 'Ranged', 'Prayer', 'Magic',
                       'Cooking', 'Woodcutting', 'Fletching', 'Fishing',
                       'Firemaking', 'Crafting', 'Smithing', 'Mining',
                       'Herblore', 'Agility', 'Thieving', 'Slayer',
                       'Farming', 'Runecrafting', 'Hunter', 'Construction',
                       'Sailing']

KC_MAPPING = {
    32: "Total Clues",
    33: "Beginner Clues",
    34: "Easy Clues",
    35: "Medium Clues",
    36: "Hard Clues",
    37: "Elite Clues",
    38: "Master Clues",
    40: "Soul Wars",
    42: "Guardians of the Rift",
    43: "Glory",
    44: "Collections logged",
    45: "Abyssal Sire",
    46: "Alchemical Hydra",
    47: "Amoxliatl",
    48: "Araxxor",
    49: "Artio",
    50: "Barrows",
    51: "Bryophita",
    52: "Callisto",
    53: "Calvar'ion",
    54: "Cerberus",
    55: "Chambers of Xeric",
    56: "Chambers of Xeric CM",
    57: "Chaos Elemental",
    58: "Chaos Fanatic",
    59: "Commander Zilyana",
    60: "Corp",
    61: "Crazy Archeologist",
    62: "Dagganoth Prime",
    63: "Dagganoth Rex",
    64: "Dagganoth Supreme",
    65: "Degranged Archeologist",
    66: "Doom",
    67: "Duke Succum",
    68: "General Graardor",
    69: "Giant Mole",
    70: "Grotesque Guardians",
    71: "Hespori",
    72: "KQ",
    73: "King Black Dragon",
    74: "Kraken",
    75: "Kree'ara",
    76: "K'ril Tsutsaroth",
    77: "Moons",
    78: "Mimic",
    79: "Nex",
    80: "Nightmare",
    81: "Phosani's Nightmare",
    82: "Obor",
    83: "Grumbler",
    84: "Sarachnis",
    85: "Scorpia",
    86: "Scurrius",
    87: "Shellbane Griffon",
    88: "Skotizo",
    89: "Sol Heredit",
    90: "Spidel",
    91: "Tempoross",
    92: "Scrub Gauntlet",
    93: "Corrupted Gauntlet",
    94: "Huey Lewis",
    95: "Leviathan",
    96: "Royal Titans",
    97: "Whisperer",
    98: "Theater of Blood",
    99: "Theater of Blood HM",
    100: "Thermy",
    101: "Normal Tombs of Amascut",
    102: "Expert Tombs of Amascut",
    103: "Zuk",
    104: "Jad",
    105: "Vardorvis",
    106: "Venenatus",
    107: "Vet'ion",
    108: "Vorkath",
    109: "The Todt",
    110: "Yama",
    111: "Zalcano",
    112: "Zulrah"
}

SKIP_LIST = [39, 40, 41, 42, 30]

GIM_MEMBERS = ['DaDuke42069', 'DaEmperor69', 'DaQueen42069', 'DaOligarch', 'VirginCape', 'Huge Weeb', 'DaSerf']
NEWSLETTER_MEMBERS = ['DaDuke42069', 'DaEmperor69', 'DaQueen42069', 'DaOligarch', 'Huge Weeb', 'DaSerf']